import aboutPage from "./../../pages/aboutPage/index";
import contact from "./../../pages/contact/index";
import donate from "./../../pages/donate/index";
import events from "./../../pages/events/index";
import eventsDetail from "./../../pages/eventsDetail/index";
import home from "./../../pages/index";
import news from "./../../pages/news/index";
import singleNews from "./../../pages/singleNewsPage/index";
import volunteer from "./../../pages/volunteer/index";

export const contact = "/contact/";
export const donate = "/donate/";
export const news = "/news/";
export const events = "/events/";
export const aboutPage = "/aboutPage/";
export const galleryPage = "/galleryPage/";
export const volunteer = "/volunteer/";
export const team = "/team/";
export const sponsors = "/sponsors/";
export const home = "/home/";
export const eventsDetail = "/eventsDetail/";
export const singleNews = "/singleNews/";
export const causesDetail = "/causesDetail/";
